[tool.poetry]
name = "gpt-your-data"
version = "0.1.0"
description = ""
authors = ["Henrique Breim <henrique@breim.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
